Repository OpenRTM/OpenRTM-aist, pull requests merged in 2019-03, with the labels that each got.

#161 Replace auto_ptr to unique_ptr
  src/lib/rtm/InPortSHMConsumer.cpp
  src/lib/rtm/OutPortSHMProvider.cpp
  src/lib/rtm/PortBase.cpp
  src/lib/rtm/SdoConfiguration.cpp
  src/lib/rtm/SdoOrganization.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
Labels: bug

#163 PeriodicECOrganization内のリファレンスカウントに関するバグに関する修正
  src/lib/rtm/PeriodicECSharedComposite.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
Labels: bug

#149 NumberingPolicyBase.cppは不要のため削除する
  src/lib/rtm/CMakeLists.txt
  src/lib/rtm/NumberingPolicyBase.cpp
Labels: bug

#153 プリプロセッサ定義の見直し
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/Composite/CMakeLists.txt
  examples/ExtTrigger/CMakeLists.txt
  src/ext/ec/artlinux/CMakeLists.txt
  src/ext/ec/logical_time/CMakeLists.txt
  src/ext/ec/rtpreempt/CMakeLists.txt
  src/ext/local_service/nameservice_file/CMakeLists.txt
  src/ext/logger/CMakeLists.txt
  src/ext/logger/fluentbit_stream/CMakeLists.txt
  src/ext/sdo/extended_fsm/CMakeLists.txt
  src/ext/sdo/fsm4rtc_observer/CMakeLists.txt
  src/ext/sdo/logger/CMakeLists.txt
  src/ext/ssl/CMakeLists.txt
  src/ext/transport/ROSTransport/CMakeLists.txt
  src/lib/coil/CMakeLists.txt
  src/lib/rtm/CMakeLists.txt
  src/lib/rtm/ext/rtmCamera/CMakeLists.txt
  src/lib/rtm/ext/rtmManipulator/CMakeLists.txt
  src/lib/rtm/idl/CMakeLists.txt
  utils/cmake/CMakeLists.txt
  utils/cmake/OpenRTMConfig_TAO.cmake.in
  utils/cmake/OpenRTMConfig_TAO_Linux.cmake.in
  utils/cmake/OpenRTMConfig_omniORB.cmake.in
  utils/cmake/OpenRTMConfig_omniORB_Linux.cmake.in
  utils/rtcd/CMakeLists.txt
  utils/rtcprof/CMakeLists.txt
  utils/rtcsh/CMakeLists.txt
Labels: bug

#151 CPU Affinity関連の問題の修正
  src/lib/coil/win32/coil/Affinity.cpp
  src/lib/rtm/Manager.cpp
  src/lib/rtm/PeriodicExecutionContext.cpp
Labels: bug

#155 Fix suspicious-string-compare
  src/lib/rtm/PeriodicECSharedComposite.cpp
Labels: bug

#184 コンポーネントオブザーバーのバグ修正(1.2)
  src/ext/sdo/observer/ComponentObserverConsumer.cpp
Labels: bug

#181 複合コンポーネントのバグ修正
  src/lib/rtm/PeriodicECSharedComposite.cpp
Labels: bug

#167 _GNU_SOURCEの再定義の警告が出ないように修正
  src/lib/rtm/MultilayerCompositeEC.cpp
  src/lib/rtm/PeriodicExecutionContext.cpp
Labels: bug

#157 C4267警告の修正
  src/lib/rtm/CORBA_RTCUtil.cpp
  src/lib/rtm/ComponentActionListener.cpp
  src/lib/rtm/ConfigAdmin.cpp
  src/lib/rtm/ConfigurationListener.cpp
  src/lib/rtm/ConnectorListener.cpp
  src/lib/rtm/CorbaNaming.cpp
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/FsmActionListener.cpp
  src/lib/rtm/InPortBase.cpp
  src/lib/rtm/ListenerHolder.h
  src/lib/rtm/LocalServiceAdmin.cpp
  src/lib/rtm/LogstreamFile.cpp
  src/lib/rtm/Manager.cpp
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/ModuleManager.cpp
  src/lib/rtm/NamingManager.cpp
  src/lib/rtm/NumberingPolicy.cpp
  src/lib/rtm/OutPort.h
  src/lib/rtm/OutPortBase.cpp
  src/lib/rtm/PeriodicECSharedComposite.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
  src/lib/rtm/PeriodicExecutionContext.cpp
  src/lib/rtm/PortAdmin.cpp
  src/lib/rtm/PortConnectListener.cpp
  src/lib/rtm/PublisherNew.cpp
  src/lib/rtm/PublisherPeriodic.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoConfiguration.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
Labels: bug

#158 C4101の警告の解消
  src/lib/rtm/CorbaNaming.cpp
  src/lib/rtm/InPortBase.cpp
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/NamingManager.cpp
  src/lib/rtm/OutPortBase.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/RTObjectStateMachine.cpp
  src/lib/rtm/SharedMemoryPort.cpp
Labels: bug

#178 ビルド時に`rtm-config: not found`を表示させないようにする
  utils/rtm-skelwrapper/rtm-skelwrapper
Labels: bug

#179 モジュールをフルパスで指定した場合に初期化関数名がおかしくなる問題の修正
  src/lib/rtm/Manager.cpp
Labels: bug

#183 コンポーネントオブザーバーのバグ修正
  src/ext/sdo/observer/ComponentObserverConsumer.cpp
Labels: bug

#187 一部のサンプルコンポーネントの文字コード、改行コードの修正
  examples/Analyzer/Analyzer.cpp
  examples/Analyzer/Analyzer.h
  examples/Analyzer/AnalyzerComp.cpp
  examples/Analyzer/Analyzer_test.cpp
  examples/Analyzer/Analyzer_test.h
  examples/Analyzer/Analyzer_testComp.cpp
Labels: bug

#188 サンプルコンポーネントの警告修正
  examples/Composite/Composite.cpp
  examples/Composite/ControllerComp.cpp
  examples/Composite/Motor.cpp
  examples/Composite/MotorComp.cpp
  examples/Composite/Sensor.cpp
  examples/Composite/SensorComp.cpp
  examples/ConfigSample/ConfigSample.cpp
  examples/ConfigSample/ConfigSampleComp.cpp
  examples/ConfigSample/VectorConvert.h
  examples/ExtTrigger/ConsoleInComp.cpp
  examples/ExtTrigger/ConsoleOutComp.cpp
  examples/SeqIO/SeqInComp.cpp
  examples/SeqIO/SeqOut.cpp
  examples/SeqIO/SeqOutComp.cpp
  examples/SimpleIO/ConsoleInComp.cpp
  examples/SimpleIO/ConsoleOutComp.cpp
  examples/SimpleService/MyServiceConsumer.cpp
  examples/SimpleService/MyServiceConsumerComp.cpp
  examples/SimpleService/MyServiceProviderComp.cpp
  examples/StaticFsm/Display.h
  examples/StaticFsm/DisplayComp.cpp
  examples/StaticFsm/InputbuttonComp.cpp
  examples/StaticFsm/MicrowaveComp.cpp
  examples/Throughput/Throughput.cpp
  examples/Throughput/ThroughputComp.cpp
  src/lib/rtm/ConnectorListener.h
  src/lib/rtm/InPort.h
Labels: bug

#190 rtcd、rtcprofの警告の修正
  utils/rtcd/rtcd_vxorks.cpp
  utils/rtcprof/rtcprof.cpp
Labels: bug

#192 OpenSSLをfind_packageで検出する
  src/ext/ssl/CMakeLists.txt
Labels: enhancement

#198 Windows、64bitの場合にos.archがunknownに設定される問題の修正
  src/lib/coil/win32/coil/OS.h
Labels: bug, enhancement

#200 rtm_skelwrapperの自動生成するコードで定数名先頭にアンダーバーが付かないように修正
  utils/rtm-skelwrapper/skel_wrapper.py
Labels: bug

#209 inet_ntoaがNULLを返した場合に落ちる可能性がある問題の修正
  src/lib/coil/posix/coil/Routing.cpp
Labels: bug, enhancement

#212 コンポーネントオブザーバーでkindsの配列のサイズを取得する部分に間違いがあったため修正(1.2)
  src/ext/sdo/observer/ComponentObserverConsumer.h
Labels: bug, priority : High

#213 コンポーネントオブザーバーでkindsの配列のサイズを取得する部分に間違いがあったため修正
  src/ext/sdo/observer/ComponentObserverConsumer.h
Labels: bug

#216 fix include guard
  src/lib/coil/posix/coil/Process.cpp
  src/lib/coil/vxworks/coil/Process.cpp
  src/lib/rtm/CdrRingBuffer.cpp
Labels: bug

#222 fsm4rtc_observer/ComponentObserverConsumerのバグ修正
  src/ext/sdo/fsm4rtc_observer/ComponentObserverConsumer.cpp
  src/ext/sdo/fsm4rtc_observer/ComponentObserverConsumer.h
Labels: bug

#223 Visual Studio 2012で未定義のアーキテクチャを削除
  src/lib/coil/win32/coil/OS.h
Labels: enhancement

#225 ソースフォルダにファイルを生成、コピーしないための修正
  examples/AutoTest/CMakeLists.txt
  examples/SimpleService/CMakeLists.txt
  src/ext/ec/logical_time/CMakeLists.txt
  src/ext/sdo/CMakeLists.txt
  src/ext/sdo/fsm4rtc_observer/CMakeLists.txt
  src/ext/sdo/logger/CMakeLists.txt
  src/ext/sdo/observer/CMakeLists.txt
  src/ext/sdo/observer/ComponentObserverConsumer.h
  src/lib/CMakeLists.txt
  src/lib/coil/CMakeLists.txt
  src/lib/rtm/CMakeLists.txt
  src/lib/rtm/ext/rtmCamera/CMakeLists.txt
  src/lib/rtm/ext/rtmManipulator/CMakeLists.txt
  src/lib/rtm/idl/CMakeLists.txt
Labels: enhancement

#236 ExecutionContextBase.hのコメントが間違っていたため修正
  src/lib/rtm/ExecutionContextBase.h
Labels: bug

#237 DitectInPortBase、DirectOutPortBase、DirectPortBaseを抽象クラスで定義する
  src/lib/rtm/DirectInPortBase.h
  src/lib/rtm/DirectOutPortBase.h
  src/lib/rtm/DirectPortBase.h
  src/lib/rtm/InPort.h
  src/lib/rtm/OutPort.h
Labels: bug

#235 [compat, modify] change static_cast to size_t
  examples/ConfigSample/ConfigSample.cpp
Labels: bug

#240 fluentbit_streamがビルドできなくなっていたため修正
  src/ext/logger/fluentbit_stream/CMakeLists.txt
Labels: bug

#241 fluentbit_streamのバグ修正
  src/ext/logger/fluentbit_stream/FluentBit.cpp
  src/lib/rtm/Manager.cpp
Labels: bug

#243 rtmの警告修正(Visual Studio、警告レベル4)
  src/lib/rtm/ByteDataStreamBase.cpp
  src/lib/rtm/CORBA_CdrMemoryStream.h
  src/lib/rtm/CORBA_IORUtil.cpp
  src/lib/rtm/CorbaNaming.cpp
  src/lib/rtm/InPortCorbaCdrConsumer.cpp
  src/lib/rtm/InPortCorbaCdrProvider.cpp
  src/lib/rtm/InPortDSConsumer.cpp
  src/lib/rtm/InPortDSProvider.cpp
  src/lib/rtm/InPortDirectProvider.cpp
  src/lib/rtm/InPortSHMConsumer.cpp
  src/lib/rtm/InPortSHMProvider.cpp
  src/lib/rtm/Manager.h
  src/lib/rtm/ManagerConfig.cpp
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/NamingServiceNumberingPolicy.cpp
  src/lib/rtm/NodeNumberingPolicy.cpp
  src/lib/rtm/OutPort.h
  src/lib/rtm/OutPortCorbaCdrConsumer.cpp
  src/lib/rtm/OutPortCorbaCdrProvider.cpp
  src/lib/rtm/OutPortDSConsumer.cpp
  src/lib/rtm/OutPortDSProvider.cpp
  src/lib/rtm/OutPortDirectConsumer.cpp
  src/lib/rtm/OutPortDirectProvider.cpp
  src/lib/rtm/OutPortProvider.cpp
  src/lib/rtm/OutPortPushConnector.cpp
  src/lib/rtm/PublisherNew.cpp
  src/lib/rtm/PublisherPeriodic.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
  src/lib/rtm/SimulatorExecutionContext.cpp
Labels: bug

#242 coilの警告修正(Visual Studio、警告レベル4)
  src/lib/coil/common/PeriodicTask.cpp
  src/lib/coil/common/PeriodicTask.h
  src/lib/coil/common/PeriodicTaskBase.h
  src/lib/coil/common/Properties.cpp
  src/lib/coil/common/Properties.h
  src/lib/coil/common/TimeMeasure.cpp
  src/lib/coil/common/TimeMeasure.h
  src/lib/coil/common/stringutil.cpp
  src/lib/coil/win32/coil/Affinity.cpp
  src/lib/coil/win32/coil/Condition.h
  src/lib/coil/win32/coil/DynamicLib.cpp
  src/lib/coil/win32/coil/File.h
  src/lib/coil/win32/coil/OS.h
  src/lib/coil/win32/coil/Process.cpp
  src/lib/coil/win32/coil/Task.cpp
  src/lib/coil/win32/coil/Time.h
  src/lib/coil/win32/coil/UUID.cpp
Labels: bug

#244 example、extの警告修正(Visual Studio、警告レベル4)
  examples/ExtTrigger/ConsoleInComp.cpp
  examples/ExtTrigger/ConsoleOutComp.cpp
  examples/SimpleIO/ConsoleInComp.cpp
  examples/SimpleIO/ConsoleOutComp.cpp
  examples/StaticFsm/DisplayComp.cpp
  examples/StaticFsm/InputbuttonComp.cpp
  examples/StaticFsm/MicrowaveComp.cpp
  examples/Throughput/Throughput.cpp
  examples/Throughput/Throughput.h
  src/ext/local_service/nameservice_file/FileNameservice.cpp
  src/ext/sdo/extended_fsm/ExtendedFsmServiceProvider.cpp
  src/ext/sdo/observer/ComponentObserverConsumer.cpp
  src/ext/transport/FastRTPS/CORBACdrDataPubSubTypes.cpp
  src/ext/transport/FastRTPS/FastRTPSManager.cpp
  src/ext/transport/FastRTPS/FastRTPSOutPort.cpp
Labels: bug

#245 ログに"ERROR: ec_base: Invoking on_shutdown() for each RTC failed."のエラーが出力される問題の修正
  src/lib/rtm/RTObject.h
Labels: bug

#247 RTC終了時に`ERROR: ec_worker: State of the RTC is not ACTIVE_STATE.`とログに出力される問題の修正
  src/lib/rtm/RTObject.h
Labels: bug

#249 forループを可能な限り範囲for文に変更する
  examples/StaticFsm/Inputbutton.cpp
  examples/StaticFsm/MicrowaveFsm.cpp
  src/ext/logger/fluentbit_stream/FluentBit.cpp
  src/ext/sdo/fsm4rtc_observer/ComponentObserverConsumer.cpp
  src/ext/transport/FastRTPS/CORBACdrDataPubSubTypes.cpp
  src/ext/transport/ROS2Transport/ROS2Serializer.h
  src/ext/transport/ROSTransport/ROSInPort.cpp
  src/ext/transport/ROSTransport/ROSOutPort.cpp
  src/ext/transport/ROSTransport/ROSSerializer.h
  src/ext/transport/ROSTransport/RosTopicManager.cpp
  src/ext/transport/ROSTransport/RosTopicManager.h
  src/lib/coil/common/Logger.cpp
  src/lib/coil/common/stringutil.h
  src/lib/coil/vxworks/coil/Affinity.cpp
  src/lib/coil/win32/coil/Affinity.cpp
  src/lib/coil/win32/coil/OS.h
  src/lib/coil/win32/coil/Process.cpp
  src/lib/rtm/ComponentActionListener.cpp
  src/lib/rtm/ConfigurationListener.cpp
  src/lib/rtm/ConnectorListener.cpp
  src/lib/rtm/CorbaPort.cpp
  src/lib/rtm/InPort.h
  src/lib/rtm/ListenerHolder.h
  src/lib/rtm/ManagerConfig.cpp
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/PortConnectListener.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
Labels: enhancement

#251 ROS2TransportのCMake実行時にエラーが発生する問題の修正
  CMakeLists.txt
Labels: bug

#253 fsm4rtc_observerをビルドするための修正
  src/ext/sdo/CMakeLists.txt
  src/ext/sdo/fsm4rtc_observer/CMakeLists.txt
Labels: enhancement

#256 [compat, modify] modify warning for extra semicolons
  examples/SeqIO/SeqIn.h
  examples/SeqIO/SeqOut.h
  examples/SimpleIO/ConsoleIn.h
  examples/SimpleIO/ConsoleOut.h
  examples/SimpleService/MyServiceConsumer.h
  examples/SimpleService/MyServiceSVC_impl.cpp
  examples/StaticFsm/Display.h
  examples/StaticFsm/Inputbutton.h
  examples/Throughput/Throughput.h
  src/ext/ec/logical_time/LogicalTimeTriggeredEC.h
  src/ext/ec/rtpreempt/RTPreemptEC.h
  src/lib/coil/common/Logger.h
  src/lib/rtm/BufferBase.h
  src/lib/rtm/CORBA_CdrMemoryStream.h
  src/lib/rtm/CORBA_RTCUtil.h
  src/lib/rtm/ConnectorListener.h
  src/lib/rtm/CorbaConsumer.h
  src/lib/rtm/DirectInPortBase.h
  src/lib/rtm/DirectPortBase.h
  src/lib/rtm/EventBase.h
  src/lib/rtm/EventPort.h
  src/lib/rtm/ExecutionContextBase.h
  src/lib/rtm/InPort.h
  src/lib/rtm/InPortConnector.h
  src/lib/rtm/LogstreamBase.h
  src/lib/rtm/LogstreamFile.h
  src/lib/rtm/Macho.h
  src/lib/rtm/Manager.h
  src/lib/rtm/NVUtil.cpp
  src/lib/rtm/NamingManager.h
  src/lib/rtm/NamingServiceNumberingPolicy.h
  src/lib/rtm/NodeNumberingPolicy.h
  src/lib/rtm/NumberingPolicy.h
  src/lib/rtm/NumberingPolicyBase.h
  src/lib/rtm/RTObject.h
  src/lib/rtm/StateMachine.h
  src/lib/rtm/StaticFSM.h
Labels: enhancement

#260 Python3でrtm-skelwrapperコマンド実行時にエラーが発生する問題の対応
  utils/rtm-skelwrapper/skel_wrapper.py
Labels: bug

#261 CMakeLists.txtのORBインクルードパスに関する修正
  CMakeLists.txt
  examples/Composite/CMakeLists.txt
  src/ext/sdo/observer/CMakeLists.txt
  src/ext/transport/ROS2Transport/CMakeLists.txt
  src/lib/rtm/CMakeLists.txt
  src/lib/rtm/ext/rtmCamera/CMakeLists.txt
  src/lib/rtm/ext/rtmManipulator/CMakeLists.txt
  src/lib/rtm/idl/CMakeLists.txt
Labels: bug

#262 #255の変更で発生したバグの修正
  src/lib/coil/common/stringutil.cpp
Labels: bug

#278 Fluent-Bit、および関連するライブラリがインストールされている前提でビルドする
  src/ext/logger/fluentbit_stream/CMakeLists.txt
Labels: bug, enhancement

#279 fluentbit_streamのバグ修正
  src/ext/logger/fluentbit_stream/FluentBit.cpp
Labels: bug

#287 sdo.service.consumer.enabled_services等のオプションが反映されない問題の修正(1.2)
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
  src/lib/rtm/SdoServiceAdmin.h
Labels: bug

#285 [compat] add newline at the end of file
  examples/ConfigSample/ConfigSampleComp.cpp
  examples/ExtTrigger/ConsoleInComp.cpp
  examples/ExtTrigger/ConsoleOutComp.cpp
  examples/SimpleService/MyServiceConsumerComp.cpp
  examples/SimpleService/MyServiceProviderComp.cpp
  examples/StaticFsm/MicrowaveComp.cpp
  src/ext/ssl/SSLTransport.cpp
  src/lib/rtm/ByteData.cpp
  src/lib/rtm/ByteData.h
  src/lib/rtm/CORBA_CdrMemoryStream.cpp
  src/lib/rtm/SimulatorExecutionContext.cpp
  src/lib/rtm/SimulatorExecutionContext.h
Labels: enhancement

#289 rtc.confで値が空白の場合に反映されない問題の修正
  src/lib/coil/common/Properties.cpp
  src/lib/coil/common/Properties.h
Labels: bug, enhancement

#296 複合コンポーネントのバグ修正
  src/lib/rtm/PeriodicECSharedComposite.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
Labels: bug

#311 [compat] modify compile option settings to select option using compil…
  CMakeLists.txt
Labels: enhancement

#313 Visual Studio、omniORBでのビルドで発生する警告の修正
  examples/StaticFsm/Inputbutton.cpp
  src/lib/coil/CMakeLists.txt
  src/lib/coil/common/Properties.cpp
  src/lib/rtm/CORBA_CdrMemoryStream.cpp
  src/lib/rtm/CORBA_IORUtil.cpp
  src/lib/rtm/InPortBase.cpp
  src/lib/rtm/InPortSHMConsumer.cpp
  src/lib/rtm/LocalServiceAdmin.cpp
  src/lib/rtm/LogstreamFile.h
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/NamingServiceNumberingPolicy.h
  src/lib/rtm/NodeNumberingPolicy.h
  src/lib/rtm/NumberingPolicy.cpp
  src/lib/rtm/NumberingPolicy.h
  src/lib/rtm/OpenHRPExecutionContext.h
  src/lib/rtm/OutPortBase.cpp
  src/lib/rtm/OutPortCorbaCdrConsumer.cpp
  src/lib/rtm/OutPortDSConsumer.cpp
  src/lib/rtm/OutPortSHMConsumer.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
  src/lib/rtm/PortAdmin.cpp
  src/lib/rtm/PortBase.cpp
  src/lib/rtm/PublisherFlush.cpp
  src/lib/rtm/PublisherFlush.h
  src/lib/rtm/PublisherNew.h
  src/lib/rtm/PublisherPeriodic.cpp
  src/lib/rtm/PublisherPeriodic.h
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoConfiguration.cpp
  src/lib/rtm/SdoOrganization.cpp
  src/lib/rtm/SdoServiceAdmin.cpp
  src/lib/rtm/SimulatorExecutionContext.h
Labels: bug
