Repository OpenRTM/OpenRTM-aist, pull requests merged in 2019-09, with the labels that each got.

#632 ByteDataクラスのメモリリークの修正
  src/lib/rtm/ByteData.cpp
Labels: bug

#633 コールバック関数でデータが変化しなかったときはバイト列を上書きしないようにする
  src/lib/rtm/ConnectorListener.h
Labels: bug, enhancement

#630 Update Microwave.cpp
  examples/StaticFsm/Display.cpp
  examples/StaticFsm/Inputbutton.cpp
  examples/StaticFsm/Microwave.cpp
  examples/Throughput/Throughput.cpp
Labels: bug

#640 データポートの通信が遅い問題の解決
  src/ext/transport/FastRTPS/FastRTPSInPort.h
  src/ext/transport/OpenSplice/OpenSpliceInPort.h
  src/ext/transport/ROSTransport/ROSInPort.cpp
  src/ext/transport/ROSTransport/ROSInPort.h
  src/lib/rtm/CORBA_CdrMemoryStream.cpp
  src/lib/rtm/ConnectorListener.cpp
  src/lib/rtm/ConnectorListener.h
  src/lib/rtm/InPort.h
  src/lib/rtm/InPortBase.cpp
  src/lib/rtm/InPortBase.h
  src/lib/rtm/InPortConnector.cpp
  src/lib/rtm/InPortConnector.h
  src/lib/rtm/InPortCorbaCdrConsumer.cpp
  src/lib/rtm/InPortCorbaCdrConsumer.h
  src/lib/rtm/InPortCorbaCdrProvider.cpp
  src/lib/rtm/InPortCorbaCdrProvider.h
  src/lib/rtm/InPortCorbaCdrUDPConsumer.cpp
  src/lib/rtm/InPortCorbaCdrUDPConsumer.h
  src/lib/rtm/InPortCorbaCdrUDPProvider.cpp
  src/lib/rtm/InPortCorbaCdrUDPProvider.h
  src/lib/rtm/InPortDSConsumer.cpp
  src/lib/rtm/InPortDSConsumer.h
  src/lib/rtm/InPortDSProvider.cpp
  src/lib/rtm/InPortDSProvider.h
  src/lib/rtm/InPortDirectProvider.h
  src/lib/rtm/InPortPullConnector.cpp
  src/lib/rtm/InPortPullConnector.h
  src/lib/rtm/InPortPushConnector.cpp
  src/lib/rtm/InPortPushConnector.h
  src/lib/rtm/InPortSHMProvider.cpp
  src/lib/rtm/InPortSHMProvider.h
  src/lib/rtm/OutPort.h
  src/lib/rtm/OutPortBase.cpp
  src/lib/rtm/OutPortBase.h
  src/lib/rtm/OutPortConnector.cpp
  src/lib/rtm/OutPortConnector.h
  src/lib/rtm/OutPortCorbaCdrConsumer.cpp
  src/lib/rtm/OutPortCorbaCdrConsumer.h
  src/lib/rtm/OutPortCorbaCdrProvider.cpp
  src/lib/rtm/OutPortCorbaCdrProvider.h
  src/lib/rtm/OutPortDSConsumer.cpp
  src/lib/rtm/OutPortDSConsumer.h
  src/lib/rtm/OutPortDSProvider.cpp
  src/lib/rtm/OutPortDSProvider.h
  src/lib/rtm/OutPortDirectProvider.h
  src/lib/rtm/OutPortPullConnector.cpp
  src/lib/rtm/OutPortPullConnector.h
  src/lib/rtm/OutPortPushConnector.cpp
  src/lib/rtm/OutPortPushConnector.h
  src/lib/rtm/OutPortSHMConsumer.h
  src/lib/rtm/OutPortSHMProvider.cpp
  src/lib/rtm/OutPortSHMProvider.h
  src/lib/rtm/PublisherFlush.cpp
  src/lib/rtm/PublisherFlush.h
  src/lib/rtm/PublisherNew.cpp
  src/lib/rtm/PublisherNew.h
  src/lib/rtm/PublisherPeriodic.cpp
  src/lib/rtm/PublisherPeriodic.h
Labels: bug, enhancement

#643 コネクタリスナのデータ変更時の動作の修正
  src/lib/rtm/ConnectorListener.h
  src/lib/rtm/InPortCorbaCdrUDPProvider.cpp
  src/lib/rtm/InPortCorbaCdrUDPProvider.h
Labels: bug

#647 [compat, modify] convert enum to enum class for ConfigurationListener
  src/ext/sdo/fsm4rtc_observer/ComponentObserverConsumer.cpp
  src/ext/sdo/observer/ComponentObserverConsumer.cpp
  src/lib/rtm/ConfigAdmin.cpp
  src/lib/rtm/ConfigurationListener.h
Labels: enhancement

#648 [compat, modify] convert enum to enum class for FsmListener
  src/ext/sdo/fsm4rtc_observer/ComponentObserverConsumer.cpp
  src/lib/rtm/FsmActionListener.h
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/RTObject.h
Labels: enhancement

#650 スレッドのCPUアフィニティを指定しない場合にログにエラーメッセージを出力しないようにする(1.2)
  src/lib/rtm/PeriodicExecutionContext.cpp
Labels: bug

#642 ManagerServantの終了処理が呼ばれない問題の修正
  src/lib/rtm/Manager.cpp
  src/lib/rtm/Manager.h
Labels: bug

#653 RTCがエラー状態から遷移しない問題の修正
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/ExecutionContextWorker.h
Labels: bug

#654 RTCがエラー状態から遷移しない問題の修正(1.2)
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/ExecutionContextWorker.h
Labels: bug

#655 ROSTransportの修正
  src/ext/transport/ROSTransport/ROSInPort.h
  src/ext/transport/ROSTransport/ROSSerializer.cpp
  src/ext/transport/ROSTransport/ROSSerializer.h
Labels: bug, enhancement

#656 ROS2Transport、FastRTPSTransportの修正
  src/ext/transport/FastRTPS/CORBACdrDataPubSubTypes.cpp
  src/ext/transport/FastRTPS/FastRTPSInPort.cpp
  src/ext/transport/FastRTPS/FastRTPSInPort.h
  src/ext/transport/FastRTPS/FastRTPSManager.cpp
  src/ext/transport/FastRTPS/FastRTPSOutPort.cpp
  src/ext/transport/ROS2Transport/ROS2Serializer.cpp
Labels: bug, enhancement
