Repository OpenRTM/OpenRTM-aist, pull requests merged in 2019-07, with the labels that each got.

#519 [compat, document] modify typo in pullrequest template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#539 Fix debug info in LogicalTimeTriggerdEC.
  src/ext/ec/logical_time/LogicalTimeTriggeredEC.cpp
Labels: bug

#541 [compat, modify] enable the unused-but-set-variable/unused-variable o…
  CMakeLists.txt
  examples/Composite/ControllerComp.cpp
  examples/Composite/MotorComp.cpp
  examples/Composite/SensorComp.cpp
  examples/ExtTrigger/ConnectorComp.cpp
  examples/SeqIO/SeqInComp.cpp
  examples/SeqIO/SeqOutComp.cpp
  examples/SimpleService/MyServiceConsumerComp.cpp
  examples/SimpleService/MyServiceProviderComp.cpp
  src/lib/rtm/NamingManager.cpp
Labels: enhancement

#542 rtc.confのパスの修正(1.2)
  src/lib/rtm/ManagerConfig.cpp
Labels: bug

#543 rtc.confのパスの修正
  src/lib/rtm/ManagerConfig.cpp
Labels: bug

#544 rqt_graphでROSTransportのPublisher、Subscriberを表示するための修正、及びバグ修正
  src/ext/transport/FastRTPS/FastRTPSInPort.cpp
  src/ext/transport/FastRTPS/FastRTPSInPort.h
  src/ext/transport/FastRTPS/FastRTPSOutPort.cpp
  src/ext/transport/OpenSplice/OpenSpliceInPort.cpp
  src/ext/transport/OpenSplice/OpenSpliceInPort.h
  src/ext/transport/OpenSplice/OpenSpliceOutPort.cpp
  src/ext/transport/ROSTransport/CMakeLists.txt
  src/ext/transport/ROSTransport/ROSInPort.cpp
  src/ext/transport/ROSTransport/ROSInPort.h
  src/ext/transport/ROSTransport/ROSOutPort.cpp
  src/ext/transport/ROSTransport/ROSOutPort.h
  src/ext/transport/ROSTransport/ROSSerializer.cpp
  src/ext/transport/ROSTransport/ROSTopicManager.cpp
  src/ext/transport/ROSTransport/ROSTopicManager.h
  src/ext/transport/ROSTransport/ROSTransport.cpp
Labels: bug, enhancement

#553 Factoryから複数スレッドで同時にオブジェクトの生成、削除を行おうとすると落ちる問題の修正
  src/lib/coil/common/coil/Factory.h
Labels: bug

#561 Manager終了時にログレベルが高いにもかかわらずPARANOIDの情報を出力する問題の修正
  src/lib/rtm/Manager.cpp
Labels: bug
