Repository OpenRTM/OpenRTM-aist, pull requests merged in 2019-10, with the labels that each got.

#659 Ubuntu+TAOでビルドするときに発生する警告の修正
  src/lib/rtm/CORBA_CdrMemoryStream.cpp
  src/lib/rtm/CORBA_CdrMemoryStream.h
  src/lib/rtm/EventPort.h
  src/lib/rtm/InPortCorbaCdrUDPConsumer.cpp
  src/lib/rtm/InPortCorbaCdrUDPConsumer.h
  src/lib/rtm/InPortCorbaCdrUDPProvider.cpp
  src/lib/rtm/InPortCorbaCdrUDPProvider.h
Labels: bug

#662 ExecutionContextWorkerでオーナーのRTCが削除されない問題の修正
  src/lib/rtm/ExecutionContextBase.cpp
Labels: bug

#664 Support clang/ninja build on Windows and fix delete bugs.
  CMakeLists.txt
  src/lib/coil/common/coil/stringutil.cpp
  src/lib/coil/win32/coil/DynamicLib.cpp
  src/lib/coil/win32/coil/DynamicLib.h
  src/lib/coil/win32/coil/OS.cpp
  src/lib/coil/win32/coil/OS.h
  src/lib/coil/win32/coil/Process.cpp
  src/lib/coil/win32/coil/Signal.h
  src/lib/rtm/ConnectorListener.h
Labels: bug

#660 A bug in notExisting() func #616
  src/lib/rtm/LocalServiceAdmin.cpp
Labels: bug

#661 Invalid overwrite read-only strings
  src/lib/rtm/OutPortBase.cpp
Labels: bug

#667 Rename Manager::main() to build with TAO.
  src/lib/rtm/Manager.cpp
  src/lib/rtm/Manager.h
Labels: bug

#665 _var型変数の使い方見直し
  examples/ExtTrigger/ConsoleInComp.cpp
  examples/ExtTrigger/ConsoleOutComp.cpp
  examples/Serializer/ConsoleInShortComp.cpp
  examples/Serializer/ConsoleOutDoubleComp.cpp
  examples/SimpleIO/ConsoleInComp.cpp
  examples/SimpleIO/ConsoleOutComp.cpp
  src/ext/ec/logical_time/example/LTTSampleComp.cpp
  src/lib/rtm/CORBA_RTCUtil.cpp
  src/lib/rtm/CORBA_RTCUtil.h
  src/lib/rtm/Manager.cpp
  src/lib/rtm/Manager.h
  src/lib/rtm/PeriodicECSharedComposite.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
  src/lib/rtm/PortBase.cpp
Labels: bug, enhancement

#666 _var型変数、_duplicate関数の使い方のミスによりオブジェクトが意図しないタイミングで削除されるバグの修正
  src/lib/rtm/CORBA_RTCUtil.cpp
  src/lib/rtm/Manager.cpp
  src/lib/rtm/PortBase.cpp
Labels: bug

#674 InPortCorbaCdrProviderのコンストラクタで発生していたメモリリークの修正
  src/lib/rtm/InPortCorbaCdrProvider.cpp
  src/lib/rtm/InPortCorbaCdrUDPProvider.cpp
  src/lib/rtm/InPortDSProvider.cpp
  src/lib/rtm/InPortSHMProvider.cpp
  src/lib/rtm/OutPortCorbaCdrProvider.cpp
  src/lib/rtm/OutPortDSProvider.cpp
  src/lib/rtm/OutPortSHMProvider.cpp
Labels: bug

#680 Make coil::Singleton's members private.
  src/lib/coil/common/coil/Singleton.h
Labels: enhancement

#681 Fix double coil::Singleton<>.
  src/lib/rtm/ExecutionContextBase.h
  src/lib/rtm/InPortConsumer.h
  src/lib/rtm/InPortProvider.h
  src/lib/rtm/LocalServiceBase.h
  src/lib/rtm/LogstreamBase.h
  src/lib/rtm/NumberingPolicyBase.h
  src/lib/rtm/OutPortProvider.h
  src/lib/rtm/PeriodicTaskFactory.h
  src/lib/rtm/PublisherBase.h
  src/lib/rtm/SdoServiceConsumerBase.h
  src/lib/rtm/SdoServiceProviderBase.h
Labels: bug

#683 InPortCorbaCdrProviderのコンストラクタで発生していたメモリリークの修正(1.2)
  src/lib/rtm/InPortCorbaCdrProvider.cpp
  src/lib/rtm/InPortSHMProvider.cpp
  src/lib/rtm/OutPortCorbaCdrProvider.cpp
  src/lib/rtm/OutPortSHMProvider.cpp
Labels: bug

#684 get_organizations関数の戻り値を_var型に入れないため発生するメモリリークの修正
  src/lib/rtm/RTObject.cpp
Labels: bug

#687 getObjRef関数内部でduplicateするための仕様変更
  src/ext/ec/logical_time/example/LTTSampleComp.cpp
  src/ext/local_service/nameservice_file/FileNameservice.cpp
  src/lib/rtm/ExecutionContextBase.cpp
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/InPortBase.cpp
  src/lib/rtm/Manager.cpp
  src/lib/rtm/ManagerServant.cpp
  src/lib/rtm/MultilayerCompositeEC.cpp
  src/lib/rtm/NamingManager.cpp
  src/lib/rtm/OutPortBase.cpp
  src/lib/rtm/PeriodicECSharedComposite.cpp
  src/lib/rtm/PeriodicECSharedComposite.h
  src/lib/rtm/PortAdmin.cpp
  src/lib/rtm/PortBase.cpp
  src/lib/rtm/PortProfileHelper.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SdoConfiguration.cpp
  src/lib/rtm/SdoOrganization.cpp
  src/lib/rtm/SdoOrganization.h
Labels: enhancement

#688 RTCが状態遷移しない問題の修正
  src/lib/rtm/ExecutionContextBase.cpp
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/ExecutionContextWorker.h
  src/lib/rtm/RTObjectStateMachine.cpp
  src/lib/rtm/RTObjectStateMachine.h
Labels: bug, enhancement

#689 RTCが状態遷移しない問題の修正(1.2)
  src/lib/rtm/ExecutionContextBase.cpp
  src/lib/rtm/ExecutionContextWorker.cpp
  src/lib/rtm/ExecutionContextWorker.h
  src/lib/rtm/RTObjectStateMachine.cpp
  src/lib/rtm/RTObjectStateMachine.h
Labels: bug, enhancement

#676 Invalid overwrite read-only strings (1.2) #661
  src/lib/rtm/OutPortBase.cpp
Labels: bug

#677 A bug in notExisting() func (1.2) #616 #660
  src/lib/rtm/LocalServiceAdmin.cpp
Labels: bug

#698 インデントがタブを使っている箇所を一部修正
  src/lib/rtm/NamingManager.cpp
  src/lib/rtm/RTObject.cpp
  src/lib/rtm/SharedMemoryPort.cpp
  src/lib/rtm/SharedMemoryPort.h
Labels: bug

#704 OpenSpliceTransportの改行コード、文字コードの修正
  src/ext/transport/OpenSplice/CORBACdrData.cpp
  src/ext/transport/OpenSplice/CORBACdrData.h
  src/ext/transport/OpenSplice/CORBACdrDataDcps.cpp
  src/ext/transport/OpenSplice/CORBACdrDataDcps.h
  src/ext/transport/OpenSplice/CORBACdrDataDcps_impl.cpp
  src/ext/transport/OpenSplice/CORBACdrDataDcps_impl.h
  src/ext/transport/OpenSplice/CORBACdrDataSplDcps.cpp
  src/ext/transport/OpenSplice/CORBACdrDataSplDcps.h
  src/ext/transport/OpenSplice/OpenSpliceManager.cpp
  src/ext/transport/OpenSplice/OpenSpliceManager.h
  src/ext/transport/OpenSplice/OpenSpliceTransport.cpp
  src/ext/transport/OpenSplice/OpenSpliceTransport.h
  src/ext/transport/OpenSplice/ccpp_CORBACdrData.h
Labels: bug

#705 _var型に値を格納すべきところで_ptr型を使用している部分の修正(#699で修正漏れした部分)
  src/lib/rtm/Manager.cpp
Labels: bug

#706 ROS2Transportの警告の修正
  src/ext/transport/ROSTransport/ROSSerializer.cpp
Labels: bug

#711 FastRTPSTransportで発生するunused parameterの警告の修正
  src/ext/transport/FastRTPS/CORBACdrDataPubSubTypes.cpp
Labels: bug

#712 OpenSpliceTransportの関数の引数の型がstd::string&となっている箇所をconst std::string&に変更
  src/ext/transport/OpenSplice/OpenSpliceManager.cpp
  src/ext/transport/OpenSplice/OpenSpliceManager.h
  src/ext/transport/OpenSplice/OpenSpliceManagerFunc.cpp
  src/ext/transport/OpenSplice/OpenSpliceManagerFunc.h
Labels: bug

#713 OpenSpliceのディレクトリの指定方法の変更
  src/ext/transport/OpenSplice/CMakeLists.txt
Labels: enhancement

#710 ROS、ROS2のImage型の画像のサイズがCameraImage型で扱えない場合にエラーにする
  src/ext/transport/ROS2Transport/ROS2Serializer.cpp
  src/ext/transport/ROSTransport/ROSSerializer.cpp
Labels: bug, enhancement

#714 FastRTPSMessageInfoの仕様変更
  src/ext/transport/FastRTPS/FastRTPSInPort.cpp
  src/ext/transport/FastRTPS/FastRTPSMessageInfo.cpp
  src/ext/transport/FastRTPS/FastRTPSMessageInfo.h
  src/ext/transport/FastRTPS/FastRTPSOutPort.cpp
  src/ext/transport/OpenSplice/OpenSpliceInPort.cpp
  src/ext/transport/OpenSplice/OpenSpliceMessageInfo.cpp
  src/ext/transport/OpenSplice/OpenSpliceMessageInfo.h
  src/ext/transport/OpenSplice/OpenSpliceOutPort.cpp
  src/ext/transport/ROS2Transport/ROS2Serializer.cpp
  src/ext/transport/ROSTransport/ROSInPort.cpp
  src/ext/transport/ROSTransport/ROSMessageInfo.cpp
  src/ext/transport/ROSTransport/ROSMessageInfo.h
  src/ext/transport/ROSTransport/ROSOutPort.cpp
  src/ext/transport/ROSTransport/ROSOutPort.h
  src/ext/transport/ROSTransport/ROSSerializer.cpp
Labels: enhancement

#716 ext以下のIDLファイル、ヘッダーファイルのインストール先を変更
  src/lib/rtm/ext/rtmCamera/CMakeLists.txt
  src/lib/rtm/ext/rtmManipulator/CMakeLists.txt
Labels: enhancement
