Repository OpenRTM/OpenRTM-aist, pull requests merged in 2019-02, with the labels that each got.

#47 #28の変更のLogStreamFileがManagerのインスタンスからプロパティを取得する箇所の修正 #46
  src/lib/rtm/LogstreamFile.cpp
Labels: enhancement

#96 可変長配列機能を使用した部分の修正
  src/lib/coil/posix/coil/File.h
  src/lib/coil/vxworks/coil/File.h
Labels: bug

#95 C4244警告の修正
  src/lib/coil/posix/coil/SharedMemory.cpp
  src/lib/coil/posix/coil/SharedMemory.h
  src/lib/coil/vxworks/coil/SharedMemory.cpp
  src/lib/coil/vxworks/coil/SharedMemory.h
  src/lib/coil/win32/coil/SharedMemory.cpp
  src/lib/coil/win32/coil/SharedMemory.h
  src/lib/rtm/CORBA_IORUtil.cpp
  src/lib/rtm/ExecutionContextWorker.h
  src/lib/rtm/ManagerServant.cpp
Labels: bug

#93 不完全型のクラスをdeleteしようとして発生する警告の修正 #80
  src/lib/rtm/EventBase.h
  src/lib/rtm/Factory.cpp
  src/lib/rtm/Factory.h
  src/lib/rtm/MultilayerCompositeEC.cpp
  src/lib/rtm/MultilayerCompositeEC.h
Labels: bug

#92 MultilayerCompositeEC.cppでRTC_ERRORの引数にイテレータを入れている問題の修正 #81
  src/lib/rtm/MultilayerCompositeEC.cpp
Labels: bug

#91 posix/OS.hの#if文の修正 #82
  src/lib/coil/posix/coil/OS.h
Labels: bug

#76 LogstreamFile.cppで定義したログレベルの文字列の定義をSystemLogger.cppに移動させる #74
  src/lib/rtm/LogstreamFile.cpp
  src/lib/rtm/SystemLogger.cpp
  src/lib/rtm/SystemLogger.h
Labels: enhancement

#75 [compat, document] fix a typo in bug_report.md
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.jp.md
  README.md
Labels: priority : Low

#42 リングバッファでバッファフルとバッファエンプティが同時に発生する問題 #41
  src/lib/rtm/RingBuffer.h
Labels: bug

#52 ModuleManagerでモジュールが存在しなかった場合の処理の変更、インデントの修正 #51
  src/lib/rtm/ModuleManager.cpp
Labels: bug

#64 rtc.conf.sampleのmanager.components.preconnect説明が古いため修正する #63
  etc/rtc.conf.sample
  src/lib/rtm/Manager.cpp
  src/lib/rtm/Manager.h
Labels: bug

#49 #28の変更でStdoutStreamクラス、StderrStreamクラス、FileStreamクラスのwrite関数の内容が同じであるため基底クラスのメンバ関数に移動する
  src/lib/rtm/LogstreamFile.cpp
  src/lib/rtm/LogstreamFile.h
Labels: enhancement

#100 Factory.hのエラーの修正
  src/lib/rtm/Factory.h
Labels: bug

#103 文字コードの修正 #102
  src/lib/rtm/ByteData.cpp
  src/lib/rtm/ByteData.h
Labels: bug

#107 仕様変更に伴うComponentObserverConsumerのエラーの修正
  src/ext/sdo/observer/ComponentObserverConsumer.h
Labels: bug

#115 同じオブジェクトファイルを複数生成しないようにする #114
  examples/Analyzer/CMakeLists.txt
  examples/AutoTest/CMakeLists.txt
  examples/CMakeLists.txt
  examples/Composite/CMakeLists.txt
  examples/ConfigSample/CMakeLists.txt
  examples/ExtTrigger/CMakeLists.txt
  examples/HelloWorld/CMakeLists.txt
  examples/SeqIO/CMakeLists.txt
  examples/SimpleIO/CMakeLists.txt
  examples/SimpleService/CMakeLists.txt
  examples/StaticFsm/CMakeLists.txt
  examples/StringIO/CMakeLists.txt
  examples/Throughput/CMakeLists.txt
  src/lib/coil/CMakeLists.txt
  src/lib/rtm/CMakeLists.txt
  src/lib/rtm/ext/rtmCamera/CMakeLists.txt
  src/lib/rtm/ext/rtmManipulator/CMakeLists.txt
Labels: bug, enhancement

#108 CMake設定ファイルのプロジェクトのバージョン、言語の設定の抜けの修正
  examples/Templates/CMakeLists.txt
  src/ext/transport/CMakeLists.txt
  src/ext/transport/ROSTransport/CMakeLists.txt
Labels: bug

#109 ルートディレクトリ直下のファイルを一部移動させる
  CMakeLists.txt
  build/cmake/Toolchain-QNX7.cmake
  build/cmake/Toolchain-vxworks6.6-Linux.cmake
  build/cmake/Toolchain-vxworks6.cmake
  build/cmake/run_munch.sh
  build/cmake/run_munch_69.sh
  build/cmake/uninstall_target.cmake.in
  build/convert_character_code.py
Labels: enhancement

#111 共有ライブラリの名前の変更(libRTC.so.2 -> libRTC.so.2.0)
  CMakeLists.txt
Labels: enhancement
